apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: api-gateway
spec:
  type: ClusterIP
  ports:
    - name: api-gateway
      port: 8222
      targetPort: 8222
  selector:
    app:  portail-entreprise
    portail-entreprise.service: api-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: api-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app:  portail-entreprise
      portail-entreprise.service: api-gateway
  template:
    metadata:
      labels:
        app:  portail-entreprise
        portail-entreprise.service: api-gateway
    spec: 
      imagePullSecrets:
        - name: harbor-creds1  
      containers:  
      - image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_api-gateway
        name: portail-api-gateway
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        ports:       
        - containerPort: 8222
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8222
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8222
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always


