apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: authentication
spec:    
  type: ClusterIP
  ports:
    - name: "1919"
      port: 1919
      targetPort: 1919
  selector:
    app: portail-entreprise
    portail-entreprise.service: authentication

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: authentication
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: authentication
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: authentication
    spec: 
      imagePullSecrets:
        - name: harbor-creds1    
      containers:
      - name: portail-authentication
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_authenticator:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        envFrom:
          - secretRef:
              name: portail-entreprise-secret
        ports:
        - containerPort: 1919
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/auth/actuator/health/readiness
            port: 1919
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/actuator/health/liveness
            port: 1919
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always
