apiVersion: v1
kind: Service
metadata:
  name: inscription
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: inscription
spec:    
  type: ClusterIP
  ports:
    - name: "1921"
      port: 1921
      targetPort: 1921
  selector:
    app: portail-entreprise
    portail-entreprise.service: inscription
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inscription
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: inscription
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: inscription
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: inscription
    spec:   
      imagePullSecrets:
        - name: harbor-creds1   
      containers:
      - name: portail-inscription
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_inscription:7455e5424572473a9f81f810a53c0bd0502934b5
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        envFrom:
          - secretRef:
              name: portail-entreprise-secret
        ports:
        - containerPort: 1921
        readinessProbe:
          httpGet:
            path: /api/inscription/actuator/health/readiness
            port: 1921
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/inscription/actuator/health/liveness
            port: 1921
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always
