apiVersion: v1
kind: Service
metadata:
  name: planning
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: planning
spec:    
  type: ClusterIP
  ports:
    - name: "1925"
      port: 1925
      targetPort: 1925
  selector:
    app: portail-entreprise
    portail-entreprise.service: planning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: planning
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: planning
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: planning
    spec:
      imagePullSecrets:
        - name: harbor-creds1 
      containers:
      - name: portail-planning
        image: harbor.pixelslabs.com/testproject/planning:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        envFrom:
          - secretRef:
              name: portail-entreprise-secret
        ports:
        - containerPort: 1925
        readinessProbe:
          httpGet:
            path: /api/planif/actuator/health/readiness
            port: 1925
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/planif/actuator/health/liveness
            port: 1925
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always
    
