apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: profile
spec:    
  type: ClusterIP
  ports:
    - name: "1920"
      port: 1920
      targetPort: 1920
  selector:
    app: portail-entreprise
    portail-entreprise.service: profile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: profile
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: profile
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: profile
    spec:
      imagePullSecrets:
        - name: harbor-creds1  
      containers:
      - name: portail-profile
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_profile:6dfe420741e2dc14056dadd94cff0a9745993114
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        envFrom:
          - secretRef:
              name: portail-entreprise-secret
        ports:
        - containerPort: 1920
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 1920
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 1920
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always
