apiVersion: v1
kind: Service
metadata:
  name: resultat
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: resultat
spec:    
  type: ClusterIP
  ports:
    - name: "1922"
      port: 1922
      targetPort: 1922
  selector:
    app: portail-entreprise
    portail-entreprise.service: resultat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultat
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: resultat
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: resultat
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: resultat
    spec:
      imagePullSecrets:
        - name: harbor-creds1      
      containers:
      - name: portail-resultat
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_resultat:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        envFrom:
          - secretRef:
              name: portail-entreprise-secret
        ports:
        - containerPort: 1922
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 1922
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 1922
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always

