apiVersion: v1
kind: Service
metadata:
  name: score
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: score
spec:    
  type: ClusterIP
  ports:
    - name: "2444"
      port: 1926
      targetPort: 1926
  selector:
    app: portail-entreprise
    portail-entreprise.service: score
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: score
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: score
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: score
    spec:
      imagePullSecrets:
        - name: harbor-creds1  
      containers:
      - name: portail-score
        image: harbor.pixelslabs.com/testproject/score:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        envFrom:
          - secretRef:
              name: portail-entreprise-secret
        ports:
        - containerPort: 1926
        readinessProbe:
          httpGet:
            path: /api/note/actuator/health/readiness
            port: 1926
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/note/actuator/health/liveness
            port: 1926
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always

    
