apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webapp-from-ingress
  namespace: esprit-portail-entreprise-dev
spec:
  podSelector:
    matchLabels:
      portail-entreprise.service: webapp
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80